services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ai-workout-api

    ports:
      - "8000:8000"

    volumes:
      - ./app:/workspace/app

    env_file:
      - .env

    depends_on:
      - postgres
      - chroma

    restart: unless-stopped

  postgres:
    image: postgres:17

    container_name: ai-workout-postgres

    environment:
      POSTGRES_DB: ai_workout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest

    container_name: ai-workout-chroma

    ports:
      - "8001:8000"

    volumes:
      - chroma_data:/data

    restart: unless-stopped

volumes:
  postgres_data:
  chroma_data: