services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ai-workout-api

    ports:
      - "8000:8000"

    volumes:
      - ./app:/workspace/app

    env_file:
      - .env

    restart: unless-stopped